server: 
  port: 2333
  address: 127.0.0.1

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false # disable default to use `youtube-plugin`
      soundcloud: true
    opusEncodingQuality: 1
    resamplingQuality: LOW
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.2.0"
      snapshot: false # Set to true if you want to use a snapshot version.

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO
